### PR TITLE
[WIP] Spark SQL API

### PR DESCRIPTION
**Pull request by zero323**
This is PR adds some useful functions including:

- `col ` - equivalent to `sql.functions.col` with dispatch for Symbols, strings, and columns
- `select`, `group-by` - `agg`, `where` 

Right now it is just a testing ground to see if there is any interest in this.

### CODE REVIEW

**Comment by sorenmacbeth** [comment]
Excellent! I'll taker a look but I'm excited to see where it goes!

**Comment by zero323** [comment]
Thanks @sorenmacbeth  I'll keep working on this then.

**Comment by crankyadmin** [comment]
I'm manually adding this patch to Flambo for my own use, it be great to see it merged. What are the changes of getting the pull request merged? I'll take some time this weekend and see if I can fix the conflict so it merges cleanly if that helps?

**Comment by sorenmacbeth** [comment]
If you can remove the merge conflicts, I don't see any problems getting it
merged in. I need to double check if it includes tests or not as well.
Finally, the master branch targets spark 2.0 and I think there were some
significant changes to sparksql there? I could be wrong.

Let's get the conflicts fixed and then evaluate.

**Comment by crankyadmin** [comment]
No problems, I'll take a look at the test this weekend as well and see if I can pull everything up to Spark 2.

**Comment by zero323** [comment]
@crankyadmin @crankyadmin  It completely slipped out of my mind. I resolved conflicts with the main branch.

Regarding 2.0.0. Since this doesn't touch statically typed datasets (not `Dataset[Row]`) there are no significant changes other than `SQLContext` being deprecated in favor of `SparkSession` and small class naming changes which affected only tests.

There is still a lot to be done though in terms of usability. Certain functions from `o.a.s.sql.functions` are quite painful to use directly.

**Comment by sorenmacbeth** [comment]
LGTM :+1:

**Pull request merged**
